### ISSUE TITLE
Tools fail to build right now

### ISSUE THREAD

**Issue by cpldcpu** [free-pdk/fppa-pdk-tools#1] opened 2019-01-06 23:19 UTC
Please note that the current repository fails to build. I tried both MSYS (windows) and a recent distribution of Mint.

The root cause is somewhat cryptic to me right now. See below.

> opcode/opcode14.c: In function 'opcode14':
include/emucpu.h:108:10: error: inlining failed in call to always_inline 'emuCPUcodeGet': function body not available
opcode/opcode14.c:10:21: note: called from here
   uint16_t opcode = emuCPUcodeGet( cpu, ePC++ ) & 0x3FFF;                                                                           //fetch next opcode and advance PC
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from opcode/opcode14.c:4:0:
include/emucpu.h:108:10: error: inlining failed in call to always_inline 'emuCPUcodeGet': function body not available
 uint16_t emuCPUcodeGet(struct emuCPU *cpu, uint16_t addr) __attribute__((always_inline));
          ^~~~~~~~~~~~~
opcode/opcode14.c:20:23: note: called from here
       case 0x0006: eA=emuCPUcodeGet(cpu,emuCPUmemGet(cpu,eSP)|(((uint16_t)emuCPUmemGet(cpu,eSP+1))<<8))&0xFF; eCycle++; break;      //LDSPTL //TODO: verify, Z?

**Comment by freepdk** [comment] 2019-01-13 17:22
Looks like you have a compiler problem.

Generally It would be nice to include a proper problem description and complete output of the make command. So others could verify / recreate your problem.

e.g. instead of "MSYS (windows)":
MSYS2 x86_64 on Windows 10 64 bit, cc = gcc 6.4.0
or instead of "rexent distribution of Mint":
Mint Tessa 64 bit, using cc = gcc / clang ...)

For me it compiles just fine (MacOS X 10.14, cc=Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0):

$ make
cc -Wall -O2 -std=c99 -Iinclude   -c -o pdkformat/pdkformat.o pdkformat/pdkformat.c
cc -Wall -O2 -std=c99 -Iinclude   -c -o emucpu/emucpu.o emucpu/emucpu.c
cc -Wall -O2 -std=c99 -Iinclude   -c -o opcode/opcode13.o opcode/opcode13.c
cc -Wall -O2 -std=c99 -Iinclude   -c -o opcode/opcode14.o opcode/opcode14.c
cc -Wall -O2 -std=c99 -Iinclude   -c -o opcode/opcode15.o opcode/opcode15.c
cc -Wall -O2 -std=c99 -Iinclude   -c -o opcode/opcode16.o opcode/opcode16.c
cc -Wall -O2 -std=c99 -Iinclude   -c -o disass/disass13.o disass/disass13.c
cc -Wall -O2 -std=c99 -Iinclude   -c -o disass/disass14.o disass/disass14.c
cc -Wall -O2 -std=c99 -Iinclude   -c -o disass/disass15.o disass/disass15.c
cc -Wall -O2 -std=c99 -Iinclude   -c -o disass/disass16.o disass/disass16.c
cc -Wall -O2 -std=c99 -Iinclude   -c -o cpuvariant/generic.o cpuvariant/generic.c
cc -Wall -O2 -std=c99 -Iinclude   -c -o cpuvariant/pmx150.o cpuvariant/pmx150.c
cc -Wall -O2 -std=c99 -Iinclude   -c -o cpuvariant/pmx154.o cpuvariant/pmx154.c
cc -Wall -O2 -std=c99 -Iinclude  -o depdk depdk.c pdkformat/pdkformat.o 
strip depdk
cc -Wall -O2 -std=c99 -Iinclude  -o dispdk dispdk.c pdkformat/pdkformat.o emucpu/emucpu.o opcode/opcode13.o opcode/opcode14.o opcode/opcode15.o opcode/opcode16.o disass/disass13.o disass/disass14.o disass/disass15.o disass/disass16.o cpuvariant/generic.o cpuvariant/pmx150.o cpuvariant/pmx154.o 
strip depdk
cc -Wall -O2 -std=c99 -Iinclude  -o emupdk emupdk.c pdkformat/pdkformat.o emucpu/emucpu.o opcode/opcode13.o opcode/opcode14.o opcode/opcode15.o opcode/opcode16.o disass/disass13.o disass/disass14.o disass/disass15.o disass/disass16.o cpuvariant/generic.o cpuvariant/pmx150.o cpuvariant/pmx154.o 
strip depdk

**Comment by spth** [comment] 2019-01-13 18:21
I can reproduce the issue using GCC 8.2.0 on Debian GNU/Linux. I'll see if I can find an easy fix tonight.

Philipp

**Comment by freepdk** [comment] 2019-01-13 18:58
fixed by PR #2 from spth.

**Closed as completed by freepdk** 2019-01-13 18:58 UTC
Labels: question
